apiVersion: core.heheh.org/v1alpha1
kind: CustomSecret
metadata:
  labels:
    app.kubernetes.io/name: custom-secret-controller
    app.kubernetes.io/managed-by: kustomize
  name: customsecret-sample
spec:
  # TODO(user): Add fields here
