apiVersion: core.heheh.org/v1alpha1
kind: CustomSecret
metadata:
  labels:
    app.kubernetes.io/name: kube-builder
    app.kubernetes.io/managed-by: kustomize
  name: customsecret-sample
spec:
  secretType: kubernetes.io/basic-auth
  rotationInterval: 60000000000